Update for newer Qt (5.5.1)
When compiled against Qt 5.5.1 an error occurs while compiling during make.
error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(&socket);
error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(socket);

Including QDataStream fixes this so that compilation is successful.